# Generated by Django 2.1 on 2018-08-25 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20180822_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(help_text='13 Character ISBN number</a>', max_length=13, verbose_name='ISBN'),
        ),
    ]
